call_parentheses = "None"
collapse_simple_statement = "Never"
column_width = 120
indent_type = "Spaces"
indent_width = 2
line_endings = "Unix"
quote_style = "AutoPreferSingle"

[sort_requires]
enabled = true
